### ISSUE TITLE
書籍 p.82 code4.9 関数stftの誤植

### ISSUE THREAD

**Issue by kjun1** [r9y9/ttslearn#10]
誤

`
M = (len(x) - N) // frame_shift + 1
`

正

`
M = (len(x) - N) // S + 1 
`

だと思われます。

**Comment by r9y9** [comment]
ご連絡ありがとうございます。おっしゃるとおりです。ソースコードを修正し、誤植リストにも加えます。対応が完了しましたら、このissueでご報告します。

**Comment by r9y9** [comment]
こちら、対応完了しました。

- PR: https://github.com/r9y9/ttslearn/pull/12
- 正誤表: https://docs.google.com/spreadsheets/d/185pTXTzCI3l4kkJTXVa4fsu6yhAwd8aury2PnLol55Q/edit?usp=sharing

ご指摘ありがとうございました。
