### ISSUE TITLE
誤植 Tacotron2 s/_init_/__init__/

### ISSUE THREAD

**Issue by tomotakatakahashi** [r9y9/ttslearn#15]
本書 p.294 記載のソースコードで、 `Tacotron2` クラスの `__init__` が誤って `_init_` と命名されているように思います。

**Comment by r9y9** [comment]
確認が遅くなり申し訳ありません。ご指摘の内容が正しいことを確認し、正誤表に反映させていただきました。ご指摘ありがとうございます。

正誤表: https://docs.google.com/spreadsheets/d/185pTXTzCI3l4kkJTXVa4fsu6yhAwd8aury2PnLol55Q/edit?usp=sharing
