### ISSUE TITLE
WaveNetの損失関数を計算する時の出力のシフト方向

### ISSUE THREAD

**Issue by zzxiang** [r9y9/ttslearn#21]
お世話になっております！

WaveNetの損失関数に関して、一つ間違っているかと思うところがあって、ご確認いただきたいです。

7.7節の最後により、WaveNetの損失関数を計算する時に、

> 自己回帰モデルとしての制約を満たすために、**出力を時間方向に一つシフト**していることに注意します。シフトしないまま損失を計算すると、WaveNetは時刻 t までの入力を元に時刻 t の音声サンプルを予測するという、本来の目的に沿わない動作をしてしまいます。時刻 t までの入力を元に、時刻 t + 1 の音声サンプルを予測することが、学習の目的であることに注意します。この問題は、WaveNetのみならず、teacher forcingを利用するその他の自己回帰モデルにも共通するため、**実装の際に十分に注意**する必要があります。

該当のソースコードcode 7.16とcode 7.17は下記です。

https://github.com/r9y9/ttslearn/blob/0fd4c04c11a2c8552198e39c0d517ef4c540b47d/notebooks/ch07_WaveNet.ipynb#L1233-L1234

https://github.com/r9y9/ttslearn/blob/0fd4c04c11a2c8552198e39c0d517ef4c540b47d/notebooks/ch07_WaveNet.ipynb#L1244

しかし、第8章のcode 8.11に、出力のシフト方向は正反対です。

https://github.com/r9y9/ttslearn/blob/0fd4c04c11a2c8552198e39c0d517ef4c540b47d/notebooks/ch08_Recipe-WaveNet.ipynb#L1300-L1301

レシピソースコードのシフト方向も同じ正反対です。

https://github.com/r9y9/ttslearn/blob/0fd4c04c11a2c8552198e39c0d517ef4c540b47d/recipes/wavenet/train_wavenet.py#L24-L27

もしかして片方が間違っているかと思っています。

自分の認識として、teacher forcingの場合、`x_hat[:, :, t]`は因果的な畳み込みで、`x[:, t]`までの音声サンプルから予測され、`x[:, t + 1]`と比較するのが正しいかと思います。なので、第8章以降の方（`x_hat[:, :, :-1], x[:, 1:]`）が正しいように思います。

しかしcode 8.11を編集して実際に実行してみた結果、`x_hat[:, :, :-1], x[:, 1:]`の損失値は`x_hat[:, :, 1:], x[:, :-1]`より大きかったです。

前者の損失値は

```
5.5439348220825195
5.494748115539551
5.402365684509277
5.309176921844482
5.262940883636475
...
```

で、後者の損失値は

```
5.043774604797363
4.923819541931152
4.949016094207764
4.854518413543701
4.862161636352539
...
```

です。

なので、どちらが正しいかはよくわからなくなります。ご確認いただけないでしょうか？

**Comment by zzxiang** [comment]
申し訳ございません！間違えて内容を書く前にissueをサブミットしました。内容を補足します！

**Comment by zzxiang** [comment]
内容を補足させていただきました！
お手数をおかけしますが、
ご確認のほど、よろしくお願いいたします！

**Comment by r9y9** [comment]
ご指摘ありがとうございます。おっしゃるとおり、code 7.16とcode 7.17 が誤りであり、一方でcode 8.11は正しいです。

> 自分の認識として、teacher forcingの場合、x_hat[:, :, t]は因果的な畳み込みで、x[:, t]までの音声サンプルから予測され、x[:, t + 1]と比較するのが正しいかと思います。なので、第8章以降の方（x_hat[:, :, :-1], x[:, 1:]）が正しいように思います。

そのとおりです。

損失関数について、誤った計算において値が大きくなってしまうのは、計算が誤っているかどうかとは関係ないと思います。気にしなくて問題ありません。

ご指摘いただいた誤りについては、修正し、正誤表を更新します。修正が完了しましたら、このissueで報告します。

**Comment by r9y9** [comment]
ソースコードを修正し、また正誤表をアップデートしました https://docs.google.com/spreadsheets/d/185pTXTzCI3l4kkJTXVa4fsu6yhAwd8aury2PnLol55Q/edit?usp=sharing

**Comment by zzxiang** [comment]
ありがとうございました！
