### ISSUE TITLE
書籍 p.262 「図6-14」は「図6-13」かと思います。

### ISSUE THREAD

**Issue by zzxiang** [r9y9/ttslearn#23]
誤

> 図6-14に示すDNN音声合成の結果

正

> 図6-13に示すDNN音声合成の結果

かと思います。実は図6-14は存在しません。

**Comment by r9y9** [comment]
ご連絡ありがとうございます。ご指摘の通りです。正誤表を更新しました。https://docs.google.com/spreadsheets/d/185pTXTzCI3l4kkJTXVa4fsu6yhAwd8aury2PnLol55Q/edit?usp=sharing

**Comment by zzxiang** [comment]
ありがとうございました！
