### ISSUE TITLE
書籍 p.263 「notebooks/ch08_Tacotron.ipynb」

### ISSUE THREAD

**Issue by zzxiang** [r9y9/ttslearn#24]
誤

> notebooks/ch08_Tacotron.ipynb

正

> notebooks/ch09_Tacotron.ipynb

だと思います。

**Comment by r9y9** [comment]
ご指摘のとおりです。ありがとうございます。正誤表を更新しました！ https://docs.google.com/spreadsheets/d/185pTXTzCI3l4kkJTXVa4fsu6yhAwd8aury2PnLol55Q/edit?usp=sharing

**Comment by zzxiang** [comment]
ありがとうございます！
