### ISSUE TITLE
Fix accent phrase border in pp_symbols

### ISSUE THREAD

**Issue by sucveria** [r9y9/ttslearn#26]
openjtalk.pyのpp_symbolsにおいて、１５１行目のアクセント句境界の条件が
        if a3 == 1 and a2_next == 1:
となっており、子音と母音の区別がないため、子音と母音の間にも区切り記号'#'が入ってしまいます。
条件に当該音素が母音、撥音、促音に該当する場合を追加して、
        if a3 == 1 and a2_next == 1 and p3 in "aeiouAEIOUNcl":
とすべきではないでしょうか。
（現実的には促音の後に区切りが入ることはないかもしれませんが）

**Comment by r9y9** [comment]
対応が遅くなってしまい誠に申し訳ございません。ご指摘の通りで正しいです。提案していただいた修正を #29 で行い、また単体テストを追加しました。

**Comment by r9y9** [comment]
https://docs.google.com/spreadsheets/d/185pTXTzCI3l4kkJTXVa4fsu6yhAwd8aury2PnLol55Q/edit?usp=sharing 正誤表をアップデートしました。 #29 をマージしました。こちらのイシューはクローズとさせていただきます。ご指摘ありがとうございました。
