### ISSUE TITLE
[誤植] ttslearn.wavenetのドキュメント s/ttslearn.dnntts/ttslearn.wavenet/

### ISSUE THREAD

**Issue by Hyado** [r9y9/ttslearn#30]
[ttslearn.wavenetのドキュメント内、TTSのExamples](https://r9y9.github.io/ttslearn/latest/wavenet.html#tts)において、
```
from ttslearn.dnntts import WaveNetTTS
```
とありますが、
```
from ttslearn.wavenet import WaveNetTTS
```
だと思われます。

**Comment by r9y9** [comment]
確認が遅くなってしまい申し訳ありません。ご指摘のとおりです。修正しました。
