### ISSUE TITLE
ttslearn.util.example_audio_file のドキュメントのExampleで、ttslearn.util.example_audio_file を使っていない

### ISSUE THREAD

**Issue by ftnext** [r9y9/ttslearn#34]
『Pythonで学ぶ音声合成』、大変興味深く、少しずつ読み進めています。

ドキュメントに軽微なミスと思われる点を見つけましたので共有します。
https://r9y9.github.io/ttslearn/latest/generated/ttslearn.util.example_audio_file.html#ttslearn.util.example_audio_file

## 現状

```
>>> fs, x = wavfile.read(pysptk.util.example_audio_file())
```

https://github.com/r9y9/ttslearn/blob/59c6f491ce205cab611e171054af43afcc6ca603/ttslearn/util.py#L91

## 修正案

```
>>> fs, x = wavfile.read(ttslearn.util.example_audio_file())
```

ttslearn.util.example_audio_fileのExampleですので、pysptk → ttslearn に返る提案です

---

example_audio_file関数をどう実装しているんだろうと気になり、ソースコードを見たときに気づきました。

**Comment by r9y9** [comment]
お返事が遅くなり申し訳ありません。ご指摘のとおりです。修正しますので、しばらくお待ち下さい。

**Comment by r9y9** [comment]
https://r9y9.github.io/ttslearn/latest/generated/ttslearn.util.example_audio_file.html#ttslearn.util.example_audio_file ドキュメントサイトのアップデートが完了しました 🙇

**Comment by ftnext** [comment]
ご対応いただきまして、ありがとうございました
