### ISSUE TITLE
第10章のレシピ1について

### ISSUE THREAD

**Issue by Maoki55** [r9y9/ttslearn#39]

**Comment by Maoki55** [comment]
初めまして、Maoki55と申します。

『Pythonで学ぶ音声合成』を参考に音声合成の学習を進めております。環境的な問題でJupyterが使用できず、無料版GoogleColabで学習しております。

質問があるのですが、第10章の「レシピstage1の実行」について、私の環境(無料版Colab)では実行した際に下図のような注意文が表示され、実行ができませんでした。

![caution](https://user-images.githubusercontent.com/65587647/182981192-ceeddb7f-21cd-4cd6-80c0-97594ea389f4.png)


試行錯誤の末、preprocess.pyの「ProcessPoolExecutor」を「ThreadPoolExecutor」に変更したら実行ができたのですが、なぜ実行できたのかが分かりません。


これの原因としては何が考えられるでしょうか？
お手数おかけしますが、ご回答よろしくお願いいたします。

**Comment by Maoki55** [comment]
以下に実行したGooleColabファイルのリンクを添付します。
参考になれば幸いです。

[https://colab.research.google.com/drive/1AZn60-3nuHHjalScwehHavI2sMuex-Sl?usp=sharing](url)

**Comment by r9y9** [comment]
確認が遅くなってしまい申し訳ありません。私も原因がわかりかねます。エラーメッセージを見るに、OpenMPか resampy に関連した問題のように見えます

**Comment by Maoki55** [comment]
ご返信ありがとうございます。
こちらでも引き続き気を付けながら学習を進めていこうと思います。
