### ISSUE TITLE
書籍 p216の図7.14が誤っている可能性が高い

### ISSUE THREAD

**Issue by y-chan** [r9y9/ttslearn#49]
p 219のコード上ではtanh関数と、sigmoid関数に通す前に、アップサンプル済み条件付け特徴量(`ca`/`cb`)が加算されていますがp216の図上ではtanh関数とsigmoid関数を通した後にアップサンプル済み条件付け特徴量の乗算をする形で書かれており、誤りであると思われます。
また同様に、スキップ接続と残差接続の部分も、加算ではなく乗算記号が使われており、誤りであると思われます。

**Comment by y-chan** [comment]
#33 にてすでに挙げられている問題でした、確認不足で申し訳ありません。closeします。
正誤表スプレッドシートに記載されていませんでしたので、記載していただけるとありがたいです。

**Comment by r9y9** [comment]
返答が遅くなり申し訳ありません。正誤表に記載しました。大変失礼しました 🙇
