### ISSUE TITLE
Error running app

### ISSUE THREAD

**Issue by Abeisas** [r9y9/ttslearn#9]
I got the message 'Error running app.' when using "/ttslearn/demo_server.py".  Any way to solve this problem?

**Comment by r9y9** [comment]
Could you give us more information? Otherwise, I cannot reproduce and fix the issue.

**Comment by Abeisas** [comment]
Thank you very much for your quick response.  Because you may be a
Japanese,  I will switch to Japanese here after.  If you may have a
problem, let me know.

たった今、サイト(https://share.streamlit.io/r9y9/ttslearn/demo_server.py)
を立ち上げたところ、正常に立ち上がりました。さきほどご報告した症状は、これまでも何回か現れていたのですが、いずれも時間がたつと消えるようです。

いずれにしろ、症状は、「サイトで音声合成をしていると突然エラーとなって、正常な画面でなく、エラー画面が出る」というものです。その後、複数回立ち上げなおしても同じエラーが出ました。先ほどはエラー画面にあるススメに従って連絡をした次第です。

安部隆士

2021年9月2日(木) 16:33 Ryuichi Yamamoto ***@***.***>:

**Comment by Abeisas** [comment]
ありがとうございました。試してみます。

安部隆士


2021年9月3日(金) 0:32 Ryuichi Yamamoto ***@***.***>:

**Comment by r9y9** [comment]
https://github.com/r9y9/ttslearn/pull/11 注意書きを記載しました。
